"use client";
import { useState } from "react";

const scenes = [["阅读","安静陪伴","清雅、微凉，不抢走你的注意力。"],["茶席","清雅相融","淡而有层次，让茶汤与香韵自然相遇。"],["独处","慢下来","温润、绵长，为一个人留一小段空白。"],["工作","清醒专注","清透的木质感，轻轻托住注意力。"],["会客","雅而有度","稳重却不压迫，让一次相见更从容。"],["睡前","温润柔和","收敛、甜润，帮你从白日里慢慢退出。"]];
const scents = {"清凉":["像雨后的森林。","清透、干净，有向上打开的感觉。","12 支相关香品"],"花香":["如花，却不像香水。","若有似无的明亮香气，轻盈而不张扬。","7 支相关香品"],"木质":["安静的木材气息。","沉稳、自然，像手掌轻轻拂过旧木。","16 支相关香品"],"醇厚":["更深，也更慢。","层次浓郁、留韵绵长，适合已熟悉沉香的人。","9 支相关香品"],"清甜":["温润的蜜意。","不直接、不腌人，从木质深处慢慢浮现。","14 支相关香品"]};
const quiz = [["你以前用过沉香吗？",["第一次","偶尔用香","经常品香"]],["你更喜欢怎样的气息？",["清爽微凉","温润清甜","安静木质","深沉浓郁"]],["你最常在什么时候用香？",["阅读 / 工作","茶席 / 会客","独处 / 睡前"]],["这次的预算是？",["200 元以内","200–500 元","500–1000 元","1000 元以上"]]];

export default function Home(){
 const[menu,setMenu]=useState(false),[bag,setBag]=useState(0),[scene,setScene]=useState(0),[scent,setScent]=useState<keyof typeof scents>("清凉"),[quizOpen,setQuizOpen]=useState(false),[step,setStep]=useState(0),[answers,setAnswers]=useState<string[]>([]),[toast,setToast]=useState(false);
 const choose=(answer:string)=>{setAnswers([...answers,answer]);setStep(step<3?step+1:4)};
 const add=()=>{setBag(bag+1);setToast(true);setTimeout(()=>setToast(false),2200)};
 return <main>
  <header className="topbar"><button className="iconButton" aria-label="打开导航" onClick={()=>setMenu(true)}><span/><span/></button><a className="brand" href="#top">沉香研习社<small>AGARWOOD STUDY</small></a><button className="bag">香囊 <b>{bag}</b></button></header>
  <section className="hero" id="top"><div className="heroImage"/><div className="heroShade"/><div className="heroCopy"><p className="eyebrow">THE STUDY OF AGARWOOD</p><h1>一缕沉香，<br/>一门关于时间的学问。</h1><p>我们寻找、品闻、记录不同产区的沉香，<br/>也与你一起，慢慢认识一支香。</p><div className="heroActions"><a className="primary" href="#scenes">开始寻香</a><a className="ghost" href="#study">初识沉香 <span>↗</span></a></div></div><a className="scrollCue" href="#scenes">慢慢往下 <i/> 01</a></section>
  <section id="scenes" className="section scenes"><p className="sectionNo">01 · BEGIN WITH LIFE</p><h2>你今天，<br/>为什么想点一支香？</h2><p className="sub">不必先懂沉香，从你此刻的生活开始。</p><div className="sceneGrid">{scenes.map((s,i)=><button key={s[0]} className={scene===i?"active":""} onClick={()=>setScene(i)}><em>0{i+1}</em><b>{s[0]}</b><span>{s[1]}</span></button>)}</div><div className="sceneNote"><small>此刻·{scenes[scene][0]}</small><p>{scenes[scene][2]}</p><a href="#product">看看适合的香 →</a></div></section>
  <section className="chooser"><div><p className="sectionNo">A PERSONAL SCENT LIST</p><h2>不知道选哪支？</h2><p>回答 4 个简单问题，<br/>找到适合你的第一支香。</p><button onClick={()=>{setQuizOpen(true);setStep(0);setAnswers([])}}>帮我选香 <span>→</span></button></div><div className="chooserArt"><i/><b>闻</b><span>04 QUESTIONS<br/>1 SCENT LIST</span></div></section>
  <section className="section scentSection"><p className="sectionNo">02 · THE SCENT MAP</p><h2>你喜欢怎样的香气？</h2><p className="sub">每一支沉香，都有自己的气息性格。</p><div className="scentMap"><i/><button className="north" onClick={()=>setScent("清凉")}>清凉</button><button className="west" onClick={()=>setScent("花香")}>花香</button><button className="east" onClick={()=>setScent("木质")}>木质</button><button className="south" onClick={()=>setScent("醇厚")}>醇厚</button><button className="center" aria-label="清甜" onClick={()=>setScent("清甜")}><span/></button></div><div className="scentDesc"><small>{scent}</small><h3>{scents[scent][0]}</h3><p>{scents[scent][1]}</p><a href="#product">{scents[scent][2]} →</a></div></section>
  <section id="product" className="product"><div className="productImg"><span>RESEARCH NO. 06</span></div><div className="productCopy"><p className="sectionNo">MEET AN INCENSE</p><h2>惠安 · 清韵</h2><p className="tags">清甜 · 微凉 · 木质</p><div className="meters">{[["清凉",4],["甜润",3],["木质",2],["醇厚",2]].map(([n,v])=><div key={n as string}><span>{n}</span><i>{[1,2,3,4,5].map(x=><b key={x} className={x<=(v as number)?"on":""}/>)}</i></div>)}</div><p className="productLine"><span>适合</span>阅读 / 茶席 / 独处</p><p className="productLine"><span>品闻难度</span>入门</p><div className="price"><b>¥ 298</b><button onClick={add}>收入香囊 ＋</button></div></div></section>
  <section id="study" className="issue"><div className="issueImage"/><div className="issueCopy"><p className="sectionNo">ISSUE 01 · 本期研习</p><h2>芽<br/>庄</h2><h3>为什么很多人第一次闻芽庄，<br/>会先记住它的“甜”？</h3><a href="#archive">从产区到香韵，开始研习 →</a></div></section>
  <section className="section process"><p className="sectionNo">03 · FROM WOOD TO INCENSE</p><h2>从一块香材，<br/>到一支香。</h2><p className="sub">我们希望你知道，手里的香从哪里来。</p><div className="timeline">{["寻香","选材","理香","制香","品鉴"].map((x,i)=><div key={x}><b>0{i+1}</b><i/><span>{x}</span></div>)}</div><a className="textLink" href="#about">了解我们的选香标准 →</a></section>
  <section id="archive" className="archive"><p className="sectionNo">CHENXIANG ARCHIVE</p><h2>沉香档案</h2><p>记录每一片产区、每一种香材、<br/>每一种典型香韵。</p><div className="archiveRail">{[["001","芽庄","清甜 / 凉"],["002","富森","醇厚 / 甜"],["003","惠安","清雅 / 甜"],["004","达拉干","浓郁 / 凉"]].map(a=><article key={a[0]}><small>ARCHIVE / {a[0]}</small><b>{a[1]}</b><span>{a[2]}</span><i>↗</i></article>)}</div></section>
  <section id="about" className="manifesto"><p className="sectionNo">WHY WE STUDY</p><h2>为什么叫<br/>“研习社”？</h2><p>我们一直觉得，沉香不是一种可以很快认识的香。</p><p>同一片产区，不同香材会有不同气息；同一块香材，也藏着不同香韵层次。</p><i/><p>所以我们寻找、品闻、记录，也不断学习。</p><b>这就是「沉香研习社」。</b></section>
  <section className="gift"><p className="sectionNo">A GIFT THAT ARRIVES SLOWLY</p><h2>以香赠人</h2><p>有些心意，适合慢慢抵达。</p><div><button>商务礼赠 <span>↗</span></button><button>长辈亲友 <span>↗</span></button><button>企业定制 <span>↗</span></button></div></section>
  <footer><a className="brand" href="#top">沉香研习社<small>AGARWOOD STUDY</small></a><p>寻香　·　研习　·　关于我们</p><p className="social">微信　小红书　视频号　抖音</p><small>© 2026 CHENXIANG STUDY</small></footer>
  <div className={`drawer ${menu?"open":""}`}><button className="close" onClick={()=>setMenu(false)}>关闭 ×</button><p>MENU / 导航</p>{["开始寻香","按香韵","按场景","沉香研习","沉香档案","关于我们"].map((x,i)=><a key={x} href={["#scenes","#product","#scenes","#study","#archive","#about"][i]} onClick={()=>setMenu(false)}><small>0{i+1}</small>{x}<span>↗</span></a>)}<button className="drawerQuiz" onClick={()=>{setMenu(false);setQuizOpen(true);setStep(0);setAnswers([])}}>帮我选香 →</button></div>
  {quizOpen&&<div className="modal" role="dialog" aria-modal="true"><div className="modalHead"><span>你的研习香单</span><button onClick={()=>setQuizOpen(false)}>×</button></div>{step<4?<div className="quiz"><p>0{step+1} / 04</p><i><b style={{width:`${(step+1)*25}%`}}/></i><h2>{quiz[step][0]}</h2><div>{quiz[step][1].map(x=><button key={x} onClick={()=>choose(x)}>{x}<span>→</span></button>)}</div>{step>0&&<button className="back" onClick={()=>{setStep(step-1);setAnswers(answers.slice(0,-1))}}>← 上一题</button>}</div>:<div className="result"><p>YOUR SCENT LIST</p><h2>找到了，<br/>你的第一支香。</h2><div><small>最适合你</small><b>惠安 · 清韵</b><span>清甜 · 微凉 · 木质</span></div><p>它不会太过张扬，却有清晰的层次。很适合作为你认识沉香的开始。</p><button onClick={()=>{setQuizOpen(false);document.getElementById("product")?.scrollIntoView()}}>认识这支香 →</button></div>}</div>}
  <div className={`toast ${toast?"show":""}`}>已收入香囊 · 惠安清韵</div>
 </main>
}
